name: 'Teste DevOps Coodesh'

on:
  workflow_dispatch:
  
permissions:
  contents: read

env:
  region: us-east-2
  environment: production
  appName: calculator

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Remove tag homepage
      run: |
        cd calculator
        sed -i '/homepage/d' package.json

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14.21.2

    - name: Build
      run: |
        cd calculator
        npm install
        npm run build
    
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: calculator/build/

  bucket:
    name: 'Create S3 bucket'
    runs-on: ubuntu-latest
    needs: build
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.2
    
    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform create new workspace
      run: | 
        terraform workspace select ${{ env.environment }} || terraform workspace new ${{ env.environment }}

    - name: Terraform Plan
      run: | 
        terraform plan -input=false -var-file=terraform.${{ env.environment }}.tfvars -out="terraform_plan"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve "terraform_plan"